#!/bin/bash

NEW_RELEASE_TAG=$(git describe HEAD --tags)
PREVIOS_RELEASE_TAG=$(git tag | grep -B1 $NEW_RELEASE_TAG | head -1)
CHANGE_LOG=$(git log $NEW_RELEASE_TAG...$PREVIOS_RELEASE_TAG)
RELEASE_DATE=$(git show $NEW_RELEASE_TAG | grep Date)
RELEASE_AUTHOR=$(git show $NEW_RELEASE_TAG | grep Author)
DESC="<#<html><head></head><body>Release:&nbsp;${NEW_RELEASE_TAG}<br>${RELEASE_DATE}<br>${RELEASE_AUTHOR}<br>${CHANGE_LOG}</body></html>#>"
CREATE_JSON="{\"queue\": \"TMP\", \"summary\": \"Dekart hw8 ${NEW_RELEASE_TAG}\", \"type\": \"task\", \"description\": \"${DESC}\"}"
FIND_JSON="{\"filter\": {\"summary\": \"Dekart hw8 ${NEW_RELEASE_TAG}\", \"queue\": \"TMP\"} }"
CURRENT_RELEASE_TICKET=$(curl -X POST https://api.tracker.yandex.net/v2/issues/_search -H 'Content-Type: application/json' -H 'Authorization: OAuth AQAAAAA74JZXAAd4ycKPSFr9UET4qtCw3Dhubj8' -H 'X-Org-ID: 6461097' -d "${FIND_JSON}")

curl -X POST https://api.tracker.yandex.net/v2/issues/ -H 'Content-Type: application/json' -H 'Authorization: OAuth AQAAAAA74JZXAAd4ycKPSFr9UET4qtCw3Dhubj8' -H 'X-Org-ID: 6461097' -d "${CREATE_JSON}"

echo $CHANGE_LOG
