# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set release info in tracker
        run: |
          NEW_RELEASE_TAG=$(git describe HEAD --tags)
          PREVIOS_RELEASE_TAG=$(git tag | grep -B1 $NEW_RELEASE_TAG | head -1)
          CHANGE_LOG=$(git log $NEW_RELEASE_TAG...$PREVIOS_RELEASE_TAG)
          RELEASE_DATE=$(git show $NEW_RELEASE_TAG | grep Date)
          RELEASE_AUTHOR=$(git show $NEW_RELEASE_TAG | grep Author)
          CREATE_JSON="{\"queue\": \"TMP\", \"summary\": \"Dekart hw8 ${NEW_RELEASE_TAG}\", \"type\": \"task\"}"
          FIND_JSON="{\"filter\": {\"summary\": \"Dekart hw8 ${NEW_RELEASE_TAG}\", \"queue\": \"TMP\"} }"
          CURRENT_RELEASE_TICKET=$(curl -X POST https://api.tracker.yandex.net/v2/issues/_search -H 'Content-Type: application/json' -H 'Authorization: OAuth ${{ secrets.TRACKER_TOKEN }}' -H 'X-Org-ID: ${{ secrets.TRACKER_ORG_ID }}' -d "${FIND_JSON}")

          if [ $CURRENT_RELEASE_TICKET == "[]" ]; then
            curl -X POST https://api.tracker.yandex.net/v2/issues/ -H 'Content-Type: application/json' -H 'Authorization: OAuth ${{ secrets.TRACKER_TOKEN }}' -H 'X-Org-ID: ${{ secrets.TRACKER_ORG_ID }}' -d "${CREATE_JSON}"
          else
            echo "exist"
          fi
